apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.deployment.appname}}-service"
  labels:
    app: "{{.Values.deployment.appname}}"
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: "{{.Values.deployment.appname}}"